image: node:6.2.0

pages:
  cache:
    paths:
    - node_modules/
    - jspm_packages/

  stage: deploy
  script:
  - npm install --no-optional
  - node_modules/.bin/jspm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master
